name: Descargar PDF y crear Release pública.

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  descargar_y_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script para descargar PDF
        run: python descargar_pdf_csj.py

      - name: Crear tag con fecha
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "Tag: $TAG"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
          echo "::set-output name=tag::$TAG"

      - name: Crear Release y subir PDF
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: escrito_csj_*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
